### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_sparse'

### ISSUE THREAD

**Issue by Zhaobailiang** [SenticNet/conv-emotion#27]
When trying to run DialogueGCN,  I faced the following  Error Issue:
Traceback (most recent call last):
  File "train_IEMOCAP.py", line 8, in <module>
    from model import MaskedNLLLoss, LSTMModel, GRUModel, DialogRNNModel, DialogueGCNModel
  File "/home/luo/zhaozhihua/conv-emotion-master/conv-emotion-master/DialogueGCN/model.py", line 6, in <module>
    from torch_geometric.nn import RGCNConv, GraphConv
  File "/home/luo/anaconda3/envs/zhaozhihua_DialogueRNN_GCN/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/luo/anaconda3/envs/zhaozhihua_DialogueRNN_GCN/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/luo/anaconda3/envs/zhaozhihua_DialogueRNN_GCN/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/luo/anaconda3/envs/zhaozhihua_DialogueRNN_GCN/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/luo/anaconda3/envs/zhaozhihua_DialogueRNN_GCN/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
ModuleNotFoundError: No module named 'torch_sparse'
![error](https://user-images.githubusercontent.com/38367601/71766879-f2224a00-2f3f-11ea-9d19-1c48f0049e74.png)

My setting :
Python 3.6.9
PyTorch 1.0.1 or 1.3.1
PyTorch Geometric 1.3.2
Pandas 0.23.0
Scikit-Learn 0.20.1
TensorFlow 1.9.0
tensorboardX 1.9.0

Could you help me solving this problem? I try many times and change pytorch version and so on. But till now I really don't know how to solve the problem. Please give me some suggestion or post the enviroment just like ‘conda env create -f environment.yml’ in the TL_ERC. Wish for your reply!

**Comment by soujanyaporia** [comment]
You can install torch-sparse using pip.
