### ISSUE TITLE
ValueError: Error when checking target: expected dense_2 to have shape (None, 4) but got array with shape (1, 1)

### ISSUE THREAD

**Issue by psaimanikanth** [SenticNet/conv-emotion#3]
**When trying to run bc-LSTM model i faced the following value Error Issue**

i have download the glove vector file and executed in my system i got the following error

Traceback (most recent call last):
  File "baseline.py", line 379, in <module>
    main()
  File "baseline.py", line 357, in main
    model.fit([u1_data,u2_data,u3_data], labels, epochs=NUM_EPOCHS, batch_size=BATCH_SIZE)
  File "C:\Anaconda3\envs\cvem\lib\site-packages\keras\engine\training.py", line 1572, in fit
    batch_size=batch_size)
  File "C:\Anaconda3\envs\cvem\lib\site-packages\keras\engine\training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "C:\Anaconda3\envs\cvem\lib\site-packages\keras\engine\training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected dense_2 to have shape (None, 4) but got array with shape (1, 1)

![image](https://user-images.githubusercontent.com/25593384/53071885-868ee400-3509-11e9-8459-be0276001b6a.png)

Could u help me solving this problem?

**Comment by soujanyaporia** [comment]
The final layer is a prediction layer which expects one hot encoding. I suggest you to first convert your labels to one hot encoded format.

**Comment by psaimanikanth** [comment]
Could you help further in detail.! i am facing issues with one hot encoding

**Comment by neverb10** [comment]
@psaimanikanth Are you able to figure this out?
