### ISSUE TITLE
ValueError: Error when checking target: expected dense_2 to have shape (4,) but got array with shape (1,)

### ISSUE THREAD

**Issue by neverb10** [SenticNet/conv-emotion#35]
**Describe the bug**
Hi I'm trying to run bc-LSTM with this command: `python3 baseline.py -config testBaseline.config`, but when trying to save the model on this [`model.fit([u1_data,u2_data,u3_data], labels, epochs=NUM_EPOCHS, batch_size=BATCH_SIZE)`](https://github.com/SenticNet/conv-emotion/blob/e9a4bae56f21a82f98fe390add35ab3661a3cfd7/bc-LSTM/baseline.py#L357), failure occurs dued to the shape of dense_2. Can you offer some help to fix ths?

related to this [bug](https://github.com/SenticNet/conv-emotion/issues/3)

log:
```
dense_2 (Dense)                 (None, 4)            1204        lstm_4[0][0]                     
==================================================================================================
Total params: 2,529,604
Trainable params: 2,524,804
Non-trainable params: 4,800
__________________________________________________________________________________________________
None
Traceback (most recent call last):
  File "baseline.py", line 379, in <module>
    main()
  File "baseline.py", line 357, in main
    model.fit([u1_data,u2_data,u3_data], labels, epochs=NUM_EPOCHS, batch_size=BATCH_SIZE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 621, in _standardize_user_data
    exception_prefix='target')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_2 to have shape (4,) but got array with shape (1,)

```

**Comment by neverb10** [comment]
@soujanyaporia Can you give a little bit more instruction on "convert your labels to one hot encoded format"?

**Comment by neverb10** [comment]
[this line](https://github.com/SenticNet/conv-emotion/blob/master/bc-LSTM/baseline.py#L313) already converts labels into one hot encoded format, not sure what to do...
